# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180413_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dpt',
            field=models.CharField(default='', max_length=20),
        ),
    ]
